openapi: 3.0.0
info:
  title: Microservicio de Clientes
  description: API para gestionar clientes en el sistema de gestión integral.
  version: 1.0.0
servers:
  - url: http://localhost:3001/api
paths:
  /clientes:
    get:
      summary: Obtener todos los clientes
      responses:
        '200':
          description: Lista de clientes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cliente'
    post:
      summary: Crear un nuevo cliente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cliente'
      responses:
        '201':
          description: Cliente creado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cliente'
  /clientes/{id}:
    get:
      summary: Obtener un cliente por ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID del cliente
          schema:
            type: string
      responses:
        '200':
          description: Cliente encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cliente'
        '404':
          description: Cliente no encontrado
    put:
      summary: Actualizar un cliente
      parameters:
        - name: id
          in: path
          required: true
          description: ID del cliente
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cliente'
      responses:
        '200':
          description: Cliente actualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cliente'
        '404':
          description: Cliente no encontrado
    delete:
      summary: Eliminar un cliente
      parameters:
        - name: id
          in: path
          required: true
          description: ID del cliente
          schema:
            type: string
      responses:
        '204':
          description: Cliente eliminado
        '404':
          description: Cliente no encontrado
components:
  schemas:
    Cliente:
      type: object
      properties:
        id:
          type: string
        nombre:
          type: string
        email:
          type: string
        telefono:
          type: string
      required:
        - nombre
        - email